services:
  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: "piko-blog-api"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DB: "postgres"
      DB_HOST: "db"
      DB_TABLE: "postgres"
      DB_PORT: "5432"
      SSL_MODE: "disable"
    ports:
      - "8080:8080"
#    depends_on:
#      db:
#        condition: service_healthy
    networks:
      - piko

volumes:
  postgres_data:

networks:
  piko:
    driver: bridge