version: '3'

tasks:
  build:
    cmds:
      - go build -o app cmd/server/main.go
      - ./app

  test:
    cmds:
      - go test -v ./..

  lint:
    cmds:
      - $HOME/go/bin/golangci-lint run

  run-docker:
    cmds:
      - docker compose -f "docker-compose.yaml" up --build -d

  start-db:
    cmds:
      - docker compose -f "docker-compose-db.yaml" up -d