version: '3'

tasks:
  build:
    cmds:
      - go build -o app cmd/server/main.go

  test:
    cmds:
      - go test -v ./..

  lint:
    cmds:
      - $HOME/go/bin/golangci-lint run

  run:
    cmds:
      - sudo docker compose -f "../docker-compose.yaml" up --build -d