-- ************************** SqlDBM: PostgreSQL *************************
-- * Generated by SqlDBM: Piko-blog-DB by nwekeejioforscheller@gmail.com *

-- ************************************** posts

CREATE TABLE posts
(
 "id"       uuid NOT NULL,
 title      string NOT NULL,
 content    text NOT NULL,
 created_at timestamp NOT NULL,
 updated_at timestamp NOT NULL,
 user_id    uuid NOT NULL,
 CONSTRAINT PK_1 PRIMARY KEY ( "id" )
);

-- CREATE INDEX FK_1 ON posts
-- (
--  user_id
-- );